package:
    name: pylauncher
    version: "{{ load_setup_py_data().version }}"
source:
    # git_tag: v0.9.7
    # git_url: https://github.psi.ch/scm/cos/pylauncher.git
    path: ..
requirements:
    build:
        - python
        - setuptools
        - pyqt
        - pyparsing
        - future
    run:
        - python
        - pyqt
        - pyparsing
        - future

build:
  noarch: python
  number: 0
  entry_points:
    - pylauncher = pylauncher.launcher:main
    - pylauncher-convert = pylauncher.convert.convert:main
    - pylauncher-protect = pylauncher.protect:main

about:
    home: https://github.psi.ch/projects/COS/repos/pylauncher/browse
    summary: "Standard PSI launcher application."
