package:
    name: pylauncher
    version: 1.1.0
source:
    # git_tag: v0.9.7
    # git_url: https://github.psi.ch/scm/cos/pylauncher.git
    path: ..
requirements:
    build:
        - setuptools
        - pyqt
        - pyparsing
        - future
    run:
        - pyqt
        - pyparsing
        - future

build:
  entry_points:
    - pylauncher = pylauncher.launcher:main
    - pylauncher-convert = pylauncher.convert.convert:main

about:
    home: https://github.psi.ch/projects/COS/repos/pylauncher/browse
    summary: "Standard PSI launcher application."
